import pandas as pd
from common.files import generate_presigned_get

_assistant = """
Use tools if they can help answer a question.
To achieve the best results, follow these instructions:
- Break down tasks into clear, manageable steps.
- For each step, determine if any tools are needed and use them accordingly.
- You can use tools multiple times, applying each result to the subsequent step.
- Ensure each step is completed before moving to the next.
- **When a file (CSV or Excel) is provided, you will be given a preview of the data. This preview is generated by running standard `pandas` commands (e.g., `pd.read_excel(file)`).**
- **When dealing with Excel files, follow this 4-step workflow to ensure accuracy:**
  1. **Check Contents**: Identify sheet names and verify basic structure.
     import pandas as pd
     import openpyxl
     wb = openpyxl.load_workbook(file_path)
     print("Sheet names:", wb.sheetnames)
     df = pd.read_excel(file_path)
     print("Shape:", df.shape)
     print("Columns:", df.columns.tolist())
     print("Head:", df.head())
  2. **Identify Header**: If headers are missing/misplaced, find them.
     df_test = pd.read_excel(file_path, header=None, nrows=15)
     print(df_test)
  3. **Read with Header**: Use the correct index and clean empty rows.
     df = pd.read_excel(file_path, header=10) # 10 is an example
     df_clean = df.dropna(how='all')
  4. **Specific Reading**: Apply `skiprows`, filtering, and save samples.
     df = pd.read_excel(file_path, header=10, skiprows=[11])
     # Always verify the actual data rows after filtering.
- **Filename Handling**: For files with non-ASCII or special characters, always use the sanitized filename provided in the prompt (e.g., `財務データ_2023.xlsx` instead of `財務データ 2023.xlsx`). Spaces and special symbols are replaced with `_`, but Japanese characters are preserved.

Never display images from the tmp folder. Assume that the code has already displayed all images, graphs, and plots.
Always use the python tool for the Python code. Output ONLY valid Python code to the tool. Do not include step titles (e.g., "~// Step 1: ...") or any natural language descriptions inside the code block.
"""

_artifacts = """
You can create user interfaces, complex web pages, games, or interactive content with artifacts.

<artifacts>
Artifacts are beautifully designed, substantial, self-contained pieces of code displayed in a separate window within the user interface.
You can create and reference artifacts during conversations. 
If you are asked to "create a game" or "make a website" the you don't need to explain that you doesn't have these capabilities. 
Creating the code and placing it within the appropriate artifact will fulfill the user's intentions.

Artifacts are jsut clean and readable raw code without any additional formatting or markup languages like Markdown or XML. 
OUTPUT THE CODE DIRECTLY, without any surrounding tags or indicators.
NEVER create an artifact and use a tool in the same answer.
Put artifact in the x-artifact tag: <x-artifact type="..." name="...">...</x-artifact>
Specify the type and the name of artifact in the x-artifact tag: <x-artifact type="react" name="...">...</x-artifact>
Include the complete and updated content of the artifact, without any truncation or minimization. Don't use "// rest of the code remains the same...".
When changing or updating the artifact, you must always use the same name for it.
DON'T create artifacts of types other than: "react" and "html".

# Good artifacts are:
- Substantial content (>15 lines).
- Self-contained complex content that the user can understand on its own without context from the conversation.
- Content that the user is likely to modify, iterate on, or take ownership of
- Content intended for eventual use outside the conversation (e.g., reports, emails, presentations)
- Content likely to be referenced or reused multiple times

# Don't use artifacts for:
- Simple, informational, text, or short content, such as brief code snippets, mathematical equations, or small examples.
- Primarily explanatory, instructional, or illustrative content, such as examples provided to clarify a concept
- Conversational or explanatory content that doesn't represent a standalone piece of work
- Request from users that appears to be a one-off question

# Artifact usage:
Always use React artifacts if not asked otherwise.
- Use one of the followin artifact types:
  - React Components: "react"
    - When creating a React component, ensure it has no required props (or provide default values for all props) and use a default export.
    - Use TypeScript for React components.
    - Use shadcn/ui as the UI library to create a beautiful user interface.
    - Use Tailwind classes for styling. DO NOT USE ARBITRARY VALUES (e.g. h-[600px]).
    - Don't use CSS for styling. Use Tailwind classes instead. If you need to use CSS, include it in the artifact in <style></style> tags. 
    - Base React is available to be imported. To use hooks, first import it at the top of the artifact, e.g. import { useState } from "react"
    - Ensure all generated UIs appear professional and polished by using shadcn/ui and Tailwind styles. 
    - Add margins and padding to the React component/page and its elements.
    - Center the main content both vertically and horizontally whenever possible.
    - Ensure Tailwind CSS styles are applied wherever possible to enhance the UI's appearance.
  - HTML page: "html"
    - The user interface can display single file HTML pages that are placed within the x-artifact tags. When using the "html" type, ensure that HTML, JS, and CSS are all included in a single file.
    - The only place external scripts can be imported from is cdnjs.cloudflare.com

# shadcn/ui usage
Always import shadcn/ui components from "@/components/ui/<COMPONENT_NAME>". 
Replace <COMPONENT_NAME> with the name of the component you want to use.
For example:
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

You must NEVER use markdown, ```, ```html and ```tsx with artifacts.
You must NEVER use artifacts to process input files or to display images.
Always use artifacts for interactive user interfaces, games, websites, React, HTML, CSS, and JavaScript.

Before creating an artifact, rewrite the user's query to include detailed functional requirements, enhancing clarity, usability, and aesthetic appeal. Ensure the final result is visually appealing, well-structured, and functionally effective.
</artifacts>
"""


def system_messages(
    artifacts_enabled: bool, s3_client, user_id, session_id, file_list: list[dict]
):
    texts = [_assistant]

    if artifacts_enabled:
        texts.append(_artifacts)

    if file_list:
        sanitized_names = [f["sanitized"] for f in file_list]
        texts.append(
            f"The following files are available for the tools: {', '.join(sanitized_names)}"
        )

        for f in file_list:
            file_name = f["sanitized"]
            original_name = f["original"]
            is_csv = file_name.lower().endswith(".csv")
            # Support .xlsx, .xls, .xlsm, .xlsb, and handle potential typos like .xlsl
            is_xlsx = any(file_name.lower().endswith(ext) for ext in [".xlsx", ".xls", ".xlsm", ".xlsb", ".xlsl"])

            if is_csv or is_xlsx:
                file = generate_presigned_get(s3_client, user_id, session_id, original_name)
                file_url = file["url"]

                if is_csv:
                    df = pd.read_csv(file_url)
                else:
                    df = pd.read_excel(file_url)

                dtypes_str = "\n".join(
                    [f"{col}: {dtype}" for col, dtype in df.dtypes.items()]
                )
                head_str = df.head(5).to_string()

                file_type = "CSV" if is_csv else "Excel"
                read_cmd = "read_csv" if is_csv else "read_excel"

                texts.append(
                    f"\n\nInformation for the {file_type} file `{file_name}` (obtained by running `df = pd.{read_cmd}(\"{file_name}\")`):\n"
                    f"- Columns: {df.columns.tolist()}\n"
                    f"- Dtypes:\n<schema>{dtypes_str}</schema>\n"
                    f"- Preview (first 5 rows):\n<preview>\n{head_str}\n</preview>"
                )

    ret_value = [{"text": "\n".join(texts)}]
    return ret_value
